# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.CharField(max_length=30, unique=True)),
                ('definition', models.CharField(max_length=30)),
                ('example', models.CharField(blank=True, max_length=500)),
                ('pronunciation', models.CharField(blank=True, max_length=1000)),
                ('phonetic_symbol', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(default='IELTS', max_length=20)),
                ('error', models.BooleanField(default=False)),
                ('known', models.BooleanField(default=False)),
            ],
        ),
    ]
