# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.CharField(max_length=30)),
                ('Chinese', models.CharField(max_length=30)),
                ('Example', models.CharField(blank=True, max_length=500)),
                ('Pronunciation', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
