# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='Chinese',
            new_name='chinese',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='English',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='Example',
            new_name='example',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='Pronunciation',
            new_name='pronunciation',
        ),
    ]
