# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180109_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(max_length=1000),
        ),
    ]
